version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Root89
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
  app:
    build: src
    ports:
      - "8080:8080"
    depends_on:
      - mysql
